// THIS FILE WAS GENERATED BY `xtp-zig-bindgen`. DO NOT EDIT.
const std = @import("std");
pub const extism = @import("extism-pdk");

const _host = struct {};

const _plugin = extism.Plugin.init(std.heap.wasm_allocator);
