[project]
name = "python_template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
dev-dependencies = [
    "pyright>=1.1.381",
    "ruff>=0.6.5",
]
