# THIS FILE WAS GENERATED BY `xtp-python-bindgen`. DO NOT EDIT.

import extism  # pyright: ignore
import plugin


# Imports


# Exports
# The implementations for these functions is in `plugin.py`


@extism.plugin_fn
def batch_compute_wf():
    res = plugin.batch_compute_wf()
    extism.output(res)
