[package]
name = "oscillator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extism-pdk = "1.0.1"

[lib]
crate_type = ["cdylib"]
